"""DATABASE changes

Revision ID: df5858be6ab0
Revises: 
Create Date: 2023-07-08 03:01:59.029792

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'df5858be6ab0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apitoken',
        sa.Column('name', sa.String(), autoincrement=False, nullable=False),
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass